<?php

namespace carono\docdoc;

class Client extends AbstractClient
{
    public function getContent($urlRequest, $data = [])
    {
        echo $this->buildUrl($urlRequest);
        return parent::getContent($urlRequest, $data); // TODO: Change the autogenerated stub
    }
}